# Generated by Django 5.1.6 on 2025-05-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0045_alter_wishlist_unique_together_wishlist_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
