# Generated by Django 5.1.6 on 2025-06-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0047_orderitem_is_returned_orderitem_return_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='return_approved',
            field=models.BooleanField(default=False),
        ),
    ]
